### ISSUE TITLE
Add @quality to note to indicate perfection, etc.

### ISSUE THREAD

**Issue by DILewis** [music-encoding/mensural-ig#2]
New attribute `@dur.quality`, applying only to notes. Values (`perfecta` | `imperfecta` | `altera` | `maior` | `minor` | `duplex` )
This should become the preferred way to perfection and alteration, with `@num` and `@numbase` only used for situations not solved by `@dur.quality`. An example would be imperfection by less than a third of the total value (i.e. by a remote part).
`duplex` applies only to notes where `@dur="longa"`

**Comment by DILewis** [comment]
If we have `duplex`, should we have `triplex` as well?

**Comment by martha-thomae** [comment]
Do you think this attribute should be part of the gestural or the logical domain? I thought logical, but the `att.duration.ratio` class (that defines the `@num` and `@numbase` attributes) is member of `att.note.ges.mensural`. So I guess, that `@dur.quality` should also be gestural.
Opinions @annplaksin, @DILewis, @lpugin, @giulianodibacco?

**Comment by annplaksin** [comment]
This is somehow a hard question for, since I am pondering about this as well. I am still not quite sure, if it is appropriate to have `@num` and `@numbase` as gestural attributes, because I used to think of gestural durations more in a way as acutual durations, not relative durations.  
That is because I see the note types which are coded as `@dur` in a very symbolic way, since they give the information about duration only when the whole context is taken into account.

But I have no problem with being convinced that they belong to the gestural domain. Currently I am just not sure.

Anyway, I think `@dur.quality` should belong to the same domain as `@num` and `@numbase`. I just would like to learn more about `@dur.quality` because I missed this conversation and am not sure myself how to apply it. (I usually use `@num` and `@numbase`.)

**Comment by DILewis** [comment]
I'm not religious about this – I think the division between domains is kind of porous, but to quote some random website (the Library of Congress text on MEI came up first when I Googled): 

> "The logical domain includes the musical content or structure including pitches, time values, articulations, dynamics, and all other elements—defined as the symbols that communicate the composer’s intentions. The gestural domain relates to a performed interpretation of the logical domain" 

In those terms, quality is unequivocally gestural, because it is a non-symbolic interpretation.

**Comment by DILewis** [comment]
@annplaksin I think that the key difference between `@dur.quality` and `@num`/`@numbase` is that the latter are indicators of duration – in the sense of "this can be sounded by counting 6 minima" – where the former indicates a process – "this breve has been imperfected [by the minim that precedes it]".
I can see why they might wind up in different categories, but I don't think they're *that* conceptually different.

**Comment by annplaksin** [comment]
@DILewis I am just not quite sure about all the possible values of `@dur.quality`, maybe because I deal usually with not so complicated cases, just with perfections, imperfections and alterations. So I just wondered what the other values are about...

But yeah, bringing up the definition again is helpful. Now we have to decide if the application of rules of imperfection/alteration is non-symbolic interpetation or applying the rules of the notation. Because it still might be a composer's intention to write something in a certain mensuration where notes are imperfected... (I am getting crazy right now, I know)

Since the borders of the domains seem rather fluent to me, we might need to to put it where it hurts least.

**Comment by DILewis** [comment]
That's where the borders become permeable – I get the impression that a composer's intention that's implicit tends to be pushed to the logical domain in a lot of core notation in MEI, but I think that's because we are more ready to assume it's 'obvious' and 'part of the notation'. 
I guess that the test I use is 'can it be ambiguous?'. If the answer is yes, then there must be interpretation (i.e. gestural). The problem with that test is that it can be overkill. 
[Is this a conversation to move to Slack?]

**Comment by annplaksin** [comment]
Yeah, move to Slack...

**Comment by giulianodibacco** [comment]
Hello and I am sorry if I am late to the discussion -- which I understand has moved to Slack? Before I write here something that is no longer needed, could please anyone explain how to join it? (I don't use Slack).

**Comment by martha-thomae** [comment]
Hi @giulianodibacco. Yes, no problem. I will answer this and the other questions in the email you sent me (first thing tomorrow morning).
